services:
  create-index:
    image: ghcr.io/elastic/elasticsearch-labs/chatbot-rag-app
    command: flask create-index
    env_file:
      - .env
    extra_hosts:
      - localhost:host-gateway

  api-frontend:
    image: ghcr.io/elastic/elasticsearch-labs/chatbot-rag-app
    depends_on:
      create-index:
        condition: service_completed_successfully
    env_file:
      - .env
    extra_hosts:
      - localhost:host-gateway
    ports:
      - "4000:4000"
