name: Set Workstream field to Evals


on:
  issues:
    types: [opened]

permissions: {}

env:
  CONTEXT_RESEARCH_PROJECT_ID: 'PVT_kwDOAGc3Zs4BbAmj'
  WORKSTREAM_FIELD_ID: 'PVTSSF_lADOAGc3Zs4BbAmjzhWPSno'
  EVALS_OPTION_ID: '6bf0df26'

jobs:
  set_workstream:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/graphql-action@ddde8ebb2493e79f390e6449c725c21663a67505 # v3.0.2
        id: add_to_project
        with:
          # Variables have to be snake cased because of https://github.com/octokit/graphql-action/issues/164
          query: |
            mutation AddToProject($project_id: ID!, $content_id: ID!) {
              addProjectV2ItemById(input: { projectId: $project_id, contentId: $content_id }) {
                item {
                  id
                }
              }
            }
          project_id: ${{ env.CONTEXT_RESEARCH_PROJECT_ID }}
          content_id: ${{ github.event.issue.node_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.CONTEXT_RESEARCH_PROJECT_TOKEN }}

      - uses: octokit/graphql-action@ddde8ebb2493e79f390e6449c725c21663a67505 # v3.0.2
        if: steps.add_to_project.outcome == 'success'
        with:
          query: |
            mutation SetWorkstream($item_id: ID!, $project_id: ID!, $field_id: ID!, $option_id: String) {
              updateProjectV2ItemFieldValue(
                input: { itemId: $item_id, projectId: $project_id, fieldId: $field_id, value: { singleSelectOptionId: $option_id } }
              ) {
                clientMutationId
              }
            }
          item_id: ${{ fromJSON(steps.add_to_project.outputs.data).addProjectV2ItemById.item.id }}
          project_id: ${{ env.CONTEXT_RESEARCH_PROJECT_ID }}
          field_id: ${{ env.WORKSTREAM_FIELD_ID }}
          option_id: ${{ env.EVALS_OPTION_ID }}
        env:
          GITHUB_TOKEN: ${{ secrets.CONTEXT_RESEARCH_PROJECT_TOKEN }}
